language: node_js

node_js:
  - '6.9.1'

cache:
  directories:
    - node_modules

install:
  - npm install -g react-native-cli
  - sh scripts/tests.sh
  - travis_debug

script:
  - npm test -- --coverage
