os: osx

language: node_js

node_js:
  - '6.9.1'

cache:
  directories:
    - node_modules

install:
  - npm install -g react-native-cli
  - sh scripts/tests.sh

script:
  - cd DemoApp/ && npm test -- --coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
